import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),handler=require('../api/community.js');
const response=()=>({code:200,headers:{},setHeader(k,v){this.headers[k]=v},status(code){this.code=code;return this},json(body){this.body=body;return this}});

test('Vercel KV credentials support read and write without additional origin configuration',async()=>{const originalFetch=globalThis.fetch;process.env.KV_REST_API_URL='https://kv.example.invalid';process.env.KV_REST_API_TOKEN='write-token';process.env.KV_REST_API_READ_ONLY_TOKEN='read-only-token';let calls=0;globalThis.fetch=async(url,options)=>{calls++;assert.equal(url,'https://kv.example.invalid');assert.equal(options.headers.Authorization,'Bearer write-token');const command=JSON.parse(options.body);return {ok:true,json:async()=>({result:command[0]==='MGET'?Array(command.length-1).fill('2'):3})};};try{let res=response();await handler({method:'GET'},res);assert.equal(res.body.enabled,true);assert.equal(res.body.votes.moron,2);res=response();await handler({method:'POST',headers:{host:'mapa.example',origin:'https://mapa.example'},body:{event:'vote',municipality:'moron'}},res);assert.equal(res.body.count,3);for(const origin of ['https://evil.example','https://mapa.example.evil.example','http://mapa.example','null',undefined]){res=response();await handler({method:'POST',headers:{host:'mapa.example',origin},body:{event:'vote',municipality:'moron'}},res);assert.equal(res.code,403);}assert.equal(calls,2);delete process.env.KV_REST_API_TOKEN;res=response();await handler({method:'GET'},res);assert.equal(res.body.enabled,false);}finally{globalThis.fetch=originalFetch;delete process.env.KV_REST_API_URL;delete process.env.KV_REST_API_TOKEN;delete process.env.KV_REST_API_READ_ONLY_TOKEN;}});

test('public votes are persisted and returned to other visitors',async()=>{const originalFetch=globalThis.fetch,store=new Map();process.env.COMMUNITY_REDIS_URL='https://example.invalid';process.env.COMMUNITY_REDIS_TOKEN='test';process.env.COMMUNITY_ORIGIN='https://example.test';globalThis.fetch=async(url,options)=>{const c=JSON.parse(options.body);let result;if(c[0]==='MGET')result=c.slice(1).map(k=>store.get(k)||null);else if(c[0]==='EVAL'){const key=c[4];result=(store.get(key)||0)+1;store.set(key,result);}else throw Error('Unexpected Redis command');return {ok:true,json:async()=>({result})};};try{let res=response();await handler({method:'POST',headers:{origin:'https://example.test'},body:{event:'vote',municipality:'moron'}},res);assert.equal(res.body.count,1);res=response();await handler({method:'GET'},res);assert.equal(res.body.votes.moron,1);assert.equal(res.body.enabled,true);res=response();await handler({method:'POST',headers:{origin:'https://example.test'},body:{event:'vote',municipality:'moron'}},res);assert.equal(res.body.count,2);res=response();await handler({method:'GET'},res);assert.equal(res.body.votes.moron,2);}finally{globalThis.fetch=originalFetch;delete process.env.COMMUNITY_REDIS_URL;delete process.env.COMMUNITY_REDIS_TOKEN;delete process.env.COMMUNITY_ORIGIN;}});
test('community disabled without credentials; app requires no backend',async()=>{delete process.env.COMMUNITY_REDIS_URL;delete process.env.COMMUNITY_REDIS_TOKEN;const res=response();await handler({method:'GET'},res);assert.equal(res.code,200);assert.equal(res.body.enabled,false);});
test('community rejects geometry and untrusted origins before storage calls',async()=>{process.env.COMMUNITY_REDIS_URL='https://example.invalid';process.env.COMMUNITY_REDIS_TOKEN='test';process.env.COMMUNITY_ORIGIN='https://example.test';let res=response();await handler({method:'POST',headers:{origin:'https://example.test'},body:{event:'simulation_created',geometry:{}}},res);assert.equal(res.code,400);res=response();await handler({method:'POST',headers:{origin:'https://evil.test'},body:{event:'simulation_created'}},res);assert.equal(res.code,403);delete process.env.COMMUNITY_REDIS_URL;delete process.env.COMMUNITY_REDIS_TOKEN;delete process.env.COMMUNITY_ORIGIN;});
