import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import fs from 'node:fs';
import {pathToFileURL} from 'node:url';
fs.mkdirSync('.checks',{recursive:true});
await build({stdin:{contents:"export * from './src/geometry.js'; export * from './src/share-state.js'; export * from './src/solar.js'; export * from './src/parcel-selection.js'; export * from './src/camera.js';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',outfile:'.checks/core.mjs'});
const {contains,footprintWithin,shadow,areaMulti,encode,decode,solar}=await import(pathToFileURL(process.cwd()+'/.checks/core.mjs'));
const {contiguous,connected,mergeParcels,screenProject,groundPoint}=await import(pathToFileURL(process.cwd()+'/.checks/core.mjs'));
const rectangle=(x,y,w=.0001,h=.0001)=>({type:'Polygon',coordinates:[[[x,y],[x+w,y],[x+w,y+h],[x,y+h],[x,y]]]});
test('only parcels sharing a side can be combined; corner and road are rejected',()=>{const a=rectangle(-58.6,-34.6),side=rectangle(-58.5999,-34.6),corner=rectangle(-58.5999,-34.5999),across=rectangle(-58.5997,-34.6);assert(contiguous(a,side));assert(!contiguous(a,corner));assert(!contiguous(a,across));assert(!connected([{geometry:a},{geometry:side},{geometry:across}]));});
test('32 mm projection is perspective, invertible on ground and orbit keeps pivot fixed',()=>{const s={flat:false,yaw:-.35,pitch:.72,panX:0,panY:0},d={width:1000,height:600,scale:2.8};for(const xy of [[10,20],[-30,40],[0,0]]){const p=screenProject(s,d,...xy),q=groundPoint(s,d,...p);assert(Math.hypot(q[0]-xy[0],q[1]-xy[1])<1e-8);}assert.deepEqual(screenProject(s,d,0,0),screenProject({...s,yaw:2},d,0,0));const a=screenProject({...s,yaw:0},d,10,50),b=screenProject({...s,yaw:0},d,10,-50);assert.notEqual(a[0],b[0]);});
const parcel={type:'Polygon',coordinates:[[[0,0],[10,0],[10,10],[6,10],[6,4],[4,4],[4,10],[0,10],[0,0]]]};
test('concave containment rejects an edge crossing the courtyard even if vertices are inside',()=>{assert(contains(parcel,[2,8]));assert(!footprintWithin(parcel,[[2,8],[8,8],[5,2]]));assert(footprintWithin(parcel,[[1,1],[3,1],[3,3],[1,3]]));});
test('holes and self intersections cannot become a building',()=>{const g={type:'Polygon',coordinates:[[[0,0],[10,0],[10,10],[0,10],[0,0]],[[4,4],[4,6],[6,6],[6,4],[4,4]]]};assert(!contains(g,[5,5]));assert(!footprintWithin(g,[[3,3],[7,3],[7,7],[3,7]]));assert(!footprintWithin(g,[[1,1],[3,3],[1,3],[3,1]]));});
test('solar clock uses coordinates and UTC-3, shadow opposite sun, no night shadow',()=>{const s=solar('2026-06-21',960,-34.592113,-58.590636,30);assert(Math.abs(s.length-96)<2);assert(s.east<0&&s.north>0);assert.notEqual(solar('2026-06-21',960,-34.65,-58.65).az,s.az);assert.deepEqual(shadow(parcel,24,{east:1,north:0,up:-1}),[]);});
test('concavity survives overhead shadow and rectangle sweep has analytic area',()=>{assert.equal(areaMulti(shadow(parcel,10,{east:0,north:0,up:1})),88);const g={type:'Polygon',coordinates:[[[0,0],[10,0],[10,10],[0,10],[0,0]]]};assert.equal(areaMulti(shadow(g,10,{east:1,north:0,up:1})),200);});
const state={schemaVersion:1,municipality:'moron',parcel:{id:'test',geometry:{type:'Polygon',coordinates:[[[-58.65,-34.65],[-58.649,-34.65],[-58.649,-34.649],[-58.65,-34.649],[-58.65,-34.65]]]}},datasetVersion:'test',footprint:null,height:24,heightMode:'floors',heightInput:8,date:'2026-06-21',minutes:960,camera:{yaw:-.35,pitch:.85,zoom:2.8,panX:0,panY:0,flat:false}};
test('versioned compressed URL restores every state value',()=>{assert.deepEqual(decode(encode(state)),state);assert(encode(state).length<JSON.stringify(state).length*1.34);});
test('corrupted, impossible date, invalid height and unsupported schema are rejected',()=>{for(const s of [{...state,schemaVersion:2},{...state,height:-1},{...state,date:'2026-02-30'},{...state,heightInput:7}])assert.throws(()=>encode(s));assert.throws(()=>decode('#v1=broken'));});

test('new floor conversion survives sharing and legacy links preserve their height',()=>{const updated={...state,height:27};assert.deepEqual(decode(encode(updated)),updated);assert.equal(decode(encode(state)).height,24);assert.throws(()=>encode({...state,height:26}));});
