import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import shp from 'shpjs';
import {unzipSync,strFromU8} from 'fflate';
import clipping from 'polygon-clipping';
import municipalities from '../config/ambaMunicipalities.json' with {type:'json'};
const id=process.argv[2],m=municipalities.find(m=>m.id===id);if(!m)throw Error('Municipio inválido');
const dir=path.join('data-source/arba',id),meta=JSON.parse(fs.readFileSync(path.join(dir,'source.json'),'utf8')),file=path.join(dir,fs.existsSync(path.join(dir,'parcelas.zip'))?'parcelas.zip':'parcelas.geojson');
let collection,originalCRS,encoding='UTF-8';
if(file.endsWith('.zip')){const bytes=fs.readFileSync(file),files=unzipSync(bytes),prjs=Object.keys(files).filter(f=>/\.prj$/i.test(f));if(prjs.length!==1)throw Error('Se requiere un solo Shape parcelario con PRJ.');originalCRS=strFromU8(files[prjs[0]]);const cpg=Object.keys(files).find(f=>/\.cpg$/i.test(f));encoding=cpg?strFromU8(files[cpg]):'No declarado por origen';collection=await shp(bytes);if(Array.isArray(collection))throw Error('ZIP con múltiples capas: separar Parcela.');}else{collection=JSON.parse(fs.readFileSync(file,'utf8'));if(meta.crs!=='EPSG:4326')throw Error('GeoJSON manual requiere crs EPSG:4326 explícito en source.json.');originalCRS=meta.crs;}
if(collection.type!=='FeatureCollection')throw Error('No es FeatureCollection');
const size=.005,cells=new Map(),ids=new Set(),clean=[],rejected=[],b=[Infinity,Infinity,-Infinity,-Infinity];
for(const [i,f]of collection.features.entries()){try{const g=f.geometry;if(!g||!['Polygon','MultiPolygon'].includes(g.type))throw Error('Geometría no poligonal');const coords=g.type==='Polygon'?[g.coordinates]:g.coordinates;for(const poly of coords)for(const ring of poly){if(ring.length<4||JSON.stringify(ring[0])!==JSON.stringify(ring.at(-1)))throw Error('Anillo abierto');for(const p of ring)if(!p.every(Number.isFinite)||p[0]<-60||p[0]>-57||p[1]<-36||p[1]>-33)throw Error('Coordenadas fuera de AMBA: revisar CRS');}const normalized=clipping.union(coords);if(!normalized.length)throw Error('Polígono vacío');const originalArea=coords.reduce((s,p)=>s+p.reduce((t,r,j)=>t+(j?-1:1)*Math.abs(r.reduce((a,v,k)=>{const q=r[(k+1)%r.length];return a+v[0]*q[1]-v[1]*q[0]},0)/2),0),0),normalizedArea=normalized.reduce((s,p)=>s+p.reduce((t,r,j)=>t+(j?-1:1)*Math.abs(r.reduce((a,v,k)=>{const q=r[(k+1)%r.length];return a+v[0]*q[1]-v[1]*q[0]},0)/2),0),0);if(originalArea<=0||Math.abs(normalizedArea-originalArea)/originalArea>.00001)throw Error('Reparación altera área; revisión manual requerida');const parcelId=String(f.properties?.CCA||f.properties?.cca||f.id||'parcela')+'-'+crypto.createHash('sha256').update(JSON.stringify(normalized)).digest('hex').slice(0,16);if(ids.has(parcelId))continue;ids.add(parcelId);const feature={type:'Feature',id:parcelId,properties:{municipality:id},geometry:{type:'MultiPolygon',coordinates:normalized}},bb=[Infinity,Infinity,-Infinity,-Infinity];for(const p of normalized.flat(2)){bb[0]=Math.min(bb[0],p[0]);bb[1]=Math.min(bb[1],p[1]);bb[2]=Math.max(bb[2],p[0]);bb[3]=Math.max(bb[3],p[1]);}if((Math.floor(bb[2]/size)-Math.floor(bb[0]/size)+1)*(Math.floor(bb[3]/size)-Math.floor(bb[1]/size)+1)>400)throw Error('Parcela demasiado extensa: requiere partición de índice');for(let x=Math.floor(bb[0]/size);x<=Math.floor(bb[2]/size);x++)for(let y=Math.floor(bb[1]/size);y<=Math.floor(bb[3]/size);y++){const key=`${x}_${y}`;if(!cells.has(key))cells.set(key,[]);cells.get(key).push(feature);}for(let j=0;j<4;j++)b[j]=j<2?Math.min(b[j],bb[j]):Math.max(b[j],bb[j]);clean.push(feature);}catch(e){rejected.push({index:i,reason:e.message});}}
fs.mkdirSync('data/amba',{recursive:true});fs.writeFileSync(path.join(dir,'validation.json'),JSON.stringify({accepted:clean.length,rejected},null,2));if(!clean.length||(rejected.length&&!process.argv.includes('--allow-quarantine')))throw Error(`${rejected.length} geometrías rechazadas. Revisar validation.json antes de publicar.`);
const hash=crypto.createHash('sha256').update(JSON.stringify(clean)).digest('hex').slice(0,12),version=`${new Date().toISOString().slice(0,10)}-${hash}`,output=path.join('data/amba',id,version);fs.mkdirSync(output,{recursive:true});for(const [key,features]of cells)fs.writeFileSync(path.join(output,key+'.json'),JSON.stringify({type:'FeatureCollection',features}));const manifestFile='data/amba/municipality-manifest.json',manifest=fs.existsSync(manifestFile)?JSON.parse(fs.readFileSync(manifestFile)):{};for(const municipality of municipalities)manifest[municipality.id]??={available:false,status:'sin-datos'};manifest[id]={source:'ARBA',sourceURL:meta.url,downloadedAt:meta.downloadedAt,publishedAt:meta.publishedAt,processedAt:new Date().toISOString(),originalCRS,encoding,version,parcelCount:clean.length,quarantinedCount:rejected.length,cellSize:size,bbox:b,available:true,status:'disponible',redistribution:meta.redistribution||'pending-review',tileCount:cells.size};fs.writeFileSync(manifestFile,JSON.stringify(manifest,null,2));console.log(id,clean.length,'parcelas',cells.size,'celdas',version);
