import {CONFIG} from '../config/app.js';
export class Community{
 constructor(){this.enabled=false;this.votes={};this.rows=new Map();}
 async init(){await this.refresh();this.timer=setInterval(()=>{if(document.getElementById('coverageDialog')?.open)this.refresh();},15000);}
 async refresh(){try{const r=await fetch(CONFIG.COMMUNITY_URL);if(!r.ok)throw Error();const s=await r.json();this.enabled=!!s.enabled;if(this.enabled){this.votes=s.votes||{};let el=document.getElementById('communityCount');if(!el){el=document.createElement('p');el.id='communityCount';document.querySelector('header').append(el);}el.textContent=`${Number(s.simulations).toLocaleString('es-AR')} simulaciones realizadas`;}}catch{this.enabled=false;}this.render();}
 voted(id){try{return !!localStorage.getItem('amba.vote.'+id);}catch{return false;}}
 render(){for(const [id,{button,count,pending}]of this.rows){button.disabled=!this.enabled||pending||this.voted(id);button.textContent=this.voted(id)?'Ya votaste':'Votar';count.textContent=this.enabled?`${Number(this.votes[id]||0).toLocaleString('es-AR')} votos`:'Total no disponible';}const status=document.getElementById('voteStatus');if(status)status.textContent=this.enabled?'Votá el próximo municipio. Los totales son públicos y se actualizan cada 15 segundos.':'La votación pública estará disponible cuando se conecte el almacenamiento compartido.';}
 addVote(row,m){const button=document.createElement('button'),count=document.createElement('span');button.className='vote-button';button.setAttribute('aria-label','Votar por '+m.name);count.className='vote-count';count.setAttribute('aria-live','polite');this.rows.set(m.id,{button,count,pending:false});button.onclick=async()=>{const entry=this.rows.get(m.id);entry.pending=true;this.render();const result=await this.event('vote',m.id);entry.pending=false;if(result){try{localStorage.setItem('amba.vote.'+m.id,'1');}catch{}this.votes[m.id]=result.count;this.render();}else{this.render();document.getElementById('voteStatus').textContent='No pudimos guardar el voto. Probá nuevamente en unos instantes.';}};row.append(button,count);this.render();}
 async event(event,municipality){if(!this.enabled)return false;try{const r=await fetch(CONFIG.COMMUNITY_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event,...(municipality?{municipality}:{})})});if(!r.ok)return false;return await r.json();}catch{return false;}}
}
export function supportAndAds(){if(CONFIG.SUPPORT_URL){const url=new URL(CONFIG.SUPPORT_URL);if(url.protocol==='https:'){const a=document.createElement('a');a.textContent='☕ Apoyar el proyecto';a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';document.querySelector('footer').append(a);}}if(CONFIG.ADS_ENABLED)for(const slot of CONFIG.AD_SLOTS){const el=document.createElement('div');el.className='ad-slot';el.dataset.slot=slot;el.setAttribute('aria-label','Espacio publicitario');el.textContent='Espacio publicitario';document.querySelector('footer').append(el);}}
