import {CONFIG} from '../config/app.js';
import {createUI} from './ui.js';
import {ParcelRepository} from './parcel-repository.js';
import {UrbanRenderer} from './renderer.js';
import {Geocoder} from './geocoder.js';
import {LocalProjects} from './local-projects.js';
import {solar} from './solar.js';
import {center,close,bounds} from './geometry.js';
import {shareURL,decode} from './share-state.js';
import QRCode from 'qrcode';
import {MapContext} from './map-context.js';
import {screenProject} from './camera.js';
import {contiguous,connected,mergeParcels} from './parcel-selection.js';
import {Community} from './community.js';
const community=new Community();community.init();
const $=id=>document.getElementById(id),b=window.Legacy;
createUI();
const repo=new ParcelRepository(),renderer=new UrbanRenderer(b),geocoder=new Geocoder(),projects=new LocalProjects();renderer.setOrigin(renderer.origin);
let active=false,municipality='tres-de-febrero',selected=null,heightMode='floors',heightInput=CONFIG.DEFAULT_FLOORS,height=0,footprint=null,request=null,loadTimer=null,start=null,searchRequest=null,version='',ready;
const contacts=new Set(),context=new MapContext();renderer.context=context;let selections=[];const instructions='Seleccioná la o las parcelas contiguas donde se ubicará la nueva construcción y luego los pisos del edificio o metros.';

const original={subtitle:document.querySelector('.brand small').textContent,heading:document.querySelector('.brand h1').innerHTML,intro:document.querySelector('header>.intro').textContent,badge:document.querySelector('.mapbadge').innerHTML,bottom:document.querySelector('.bottom').innerHTML};
const message=text=>$('urbanMessage').textContent=text;
const safe=fn=>async(...args)=>{try{return await fn(...args)}catch(e){message(e.message);}};
function setActive(value){active=value;document.body.classList.toggle('urban-active',value);document.title=value?'Mapa de sombras · AMBA':'Mapa de sombras · AMBA';document.querySelector('.brand small').textContent=value?'Tres de Febrero · Provincia de Buenos Aires':original.subtitle;b.stop();b.setSimulation('sun');$('explorer').hidden=!value;$('parcelPanel').hidden=!value||!selected;$('datasetCredit').hidden=!value;document.querySelector('.sound-modes').hidden=value;document.querySelector('[data-base]').closest('.viewtoggle').hidden=value;document.querySelector('.brand h1').innerHTML=value?'Mapa de sombras <span>· AMBA</span>':original.heading;document.querySelector('.mapbadge').innerHTML=value?'Parcelario ARBA · norte geográfico':original.badge;document.querySelector('.bottom').innerHTML=value?'<span>Coordenadas geográficas · proyección local en metros</span><span>Estudio exploratorio</span>':original.bottom;b.update();}
function sync(){renderer.selected=selected;renderer.selectedIds=new Set(selections.map(f=>String(f.id)));renderer.footprint=footprint;renderer.height=height;$('parcelPanel').hidden=!active||!selected;$('selectedLabel').textContent=selections.length===1?'1 parcela seleccionada':`${selections.length} parcelas contiguas seleccionadas`;$('selectedLabel').title=selected?.id||'';$('simulationActions').hidden=!height;$('generate').disabled=!footprint;$('view3d').disabled=!height;$('view3d').title=height?'Girar alrededor del edificio':'Generá el volumen para habilitar 3D';$('buildingHeight').value=heightInput;$('buildingHeight').step=heightMode==='floors'?'1':'0.1';$('buildingHeight').min=heightMode==='floors'?'1':'0.1';$('buildingHeight').max=String(CONFIG.MAX_HEIGHT/(heightMode==='floors'?CONFIG.DEFAULT_FLOOR_HEIGHT:1));$('heightMode').value=heightMode;$('heightEquivalent').textContent=heightMode==='floors'?`${heightInput} pisos ≈ ${heightInput*CONFIG.DEFAULT_FLOOR_HEIGHT} m`:`${heightInput} m`;$('geoDebug').hidden=!CONFIG.DEBUG;if(selected)$('geoDebug').textContent=JSON.stringify({id:selected.id,coordinates:center(selected.geometry),bbox:bounds(selected.geometry),crs:'EPSG:4326',originalCRS:repo.manifest[municipality]?.originalCRS},null,2);b.update();}
function applyView(flat){if(!flat&&!height)return;const zoom=b.state.zoom;if(!flat&&selected){renderer.setOrigin(center(footprint||selected.geometry));b.state.panX=b.state.panY=0;}Object.assign(b.state,{flat,yaw:flat?0:-.35,pitch:.72,zoom});for(const [id,on]of [['view2d',flat],['view3d',!flat]]){$(id).classList.toggle('active',on);$(id).setAttribute('aria-pressed',String(on));}document.querySelector('.maphint').textContent=flat?'Arrastrá para desplazarte · doble clic para acercar':'Arrastrá para girar alrededor del edificio · perspectiva 32 mm';b.draw();}
function fitMunicipality(){const box=context.boundary?bounds(context.boundary):repo.manifest[municipality].bbox,origin=[(box[0]+box[2])/2,(box[1]+box[3])/2];renderer.setOrigin(origin);const {width:W,height:H}=b.dimensions(),a=renderer.projection.forward(box.slice(0,2)),z=renderer.projection.forward(box.slice(2)),target=Math.min(W*.8/(z[0]-a[0]),H*.72/(z[1]-a[1]));Object.assign(b.state,{panX:0,panY:0,zoom:Math.max(.006,target/(Math.min(W,H)/480))});applyView(true);}
async function loadViewport(){if(!active)return;request?.abort();const controller=new AbortController();request=controller;const {width:W,height:H}=b.dimensions(),rect=b.canvas.getBoundingClientRect(),ps=[[0,0],[W,0],[0,H],[W,H]].map(p=>renderer.point(rect.left+p[0],rect.top+p[1])),box=[Math.min(...ps.map(p=>p[0])),Math.min(...ps.map(p=>p[1])),Math.max(...ps.map(p=>p[0])),Math.max(...ps.map(p=>p[1]))];const wide=b.state.zoom<.4;try{const [features,places]=await Promise.all([wide?Promise.resolve([]):repo.viewport(municipality,box,controller.signal),context.load(municipality,box,controller.signal,wide)]);if(controller.signal.aborted)return;renderer.features=features;context.features=places;for(const f of selections)if(!features.some(p=>p.id===f.id))renderer.features.push(f);if(!selected)message(wide?'Tres de Febrero · acercá el mapa o buscá una dirección para seleccionar parcelas.':instructions);b.draw();}catch(e){if(e.name!=='AbortError')message(e.message);}}
function scheduleLoad(){clearTimeout(loadTimer);loadTimer=setTimeout(loadViewport,250);}
async function changeMunicipality(id){if(!CONFIG.ENABLED_MUNICIPALITIES.includes(id)){message('Por ahora está habilitado solo Tres de Febrero.');return;}request?.abort();municipality=id;selected=null;selections=[];footprint=null;height=0;heightMode='floors';heightInput=CONFIG.DEFAULT_FLOORS;renderer.features=[];renderer.marker=null;version=repo.manifest[id]?.version||'';fitMunicipality();sync();const data=repo.manifest[id];$('datasetCredit').textContent=data?.available?'Parcelario: ARBA · actualización '+data.publishedAt+' · Calles y referencias: © OpenStreetMap contributors':'Parcelario todavía no disponible.';await loadViewport();}
function choose(f){const id=String(f.id),existing=selections.findIndex(p=>String(p.id)===id);let next;if(existing>=0){next=selections.filter((_,i)=>i!==existing);if(!connected(next)){message('No se puede quitar esa parcela porque separaría las restantes.');return;}}else{if(selections.length>=16){message('Podés seleccionar hasta 16 parcelas contiguas.');return;}if(selections.length&&!selections.some(p=>contiguous(p.geometry,f.geometry))){message('La parcela debe compartir un lado con las seleccionadas. No se pueden unir lotes separados por una calle o solo por una esquina.');return;}next=[...selections,f];}selections=next;selected=mergeParcels(selections);version=repo.manifest[municipality]?.version||version;footprint=selected?.geometry||null;height=0;applyView(true);sync();message(instructions);}
function getHeight(){const n=Number($('buildingHeight').value),mode=$('heightMode').value,h=n*(mode==='floors'?CONFIG.DEFAULT_FLOOR_HEIGHT:1);if(!Number.isFinite(h)||h<=0||h>CONFIG.MAX_HEIGHT||(mode==='floors'&&!Number.isInteger(n)))throw Error(`Ingresá una altura entre 0 y ${CONFIG.MAX_HEIGHT} m, o pisos enteros equivalentes.`);return {n,mode,h};}
function snapshot(){if(!selected||!height)throw Error('Generá un volumen antes de guardar o compartir.');return {schemaVersion:1,municipality,parcel:{id:String(selected.id),geometry:selected.geometry},datasetVersion:version,footprint:footprint===selected.geometry?null:footprint.coordinates[0].slice(0,-1),height,heightMode,heightInput,date:b.state.date,minutes:Math.round(b.state.minutes),parcels:selections.map(f=>({id:String(f.id),geometry:f.geometry})),camera:Object.fromEntries(['yaw','pitch','zoom','panX','panY','flat'].map(k=>[k,b.state[k]]))};}
async function restore(s){await ready;municipality=s.municipality;$('municipality').value=municipality;selected={type:'Feature',id:s.parcel.id,properties:{municipality},geometry:s.parcel.geometry};version=s.datasetVersion;height=s.height;heightInput=s.heightInput;heightMode=s.heightMode;if(heightMode==='floors'&&Math.abs(heightInput*CONFIG.DEFAULT_FLOOR_HEIGHT-height)>1e-6){heightMode='meters';heightInput=height;}footprint=s.footprint?{type:'Polygon',coordinates:[close(s.footprint)]}:selected.geometry;selections=(s.parcels||[s.parcel]).map(p=>({type:'Feature',id:p.id,properties:{municipality},geometry:p.geometry}));renderer.setOrigin(center(footprint));renderer.features=[...selections];setActive(true);Object.assign(b.state,s.camera,{flat:true,yaw:0,date:s.date,minutes:s.minutes});applyView(true);$('date').value=s.date;sync();await loadViewport();if(repo.manifest[municipality]?.version!==version)message('El dataset cambió o no está disponible. Conservamos la geometría original del enlace.');$('openFull').href=shareURL(s);}
function pointerDown(e){if(!active)return false;contacts.add(e.pointerId);if(contacts.size>1){start=null;return false;}start={x:e.clientX,y:e.clientY,id:e.pointerId};return false;}
function pointerMove(e){if(!active)return false;if(!e.buttons){const f=repo.find(renderer.features,renderer.point(e.clientX,e.clientY));if(renderer.hover!==f?.id){renderer.hover=f?.id;b.draw();}}return false;}
function pointerUp(e){contacts.delete(e.pointerId);if(!active||!start||start.id!==e.pointerId)return;const tap=e.type!=='pointercancel'&&Math.hypot(e.clientX-start.x,e.clientY-start.y)<6;start=null;if(tap){const f=repo.find(renderer.features,renderer.point(e.clientX,e.clientY));if(f)choose(f);else if(b.state.zoom<.4){renderer.setOrigin(renderer.point(e.clientX,e.clientY));b.state.panX=b.state.panY=0;b.state.zoom=Math.min(2.8,b.state.zoom*5);b.draw();scheduleLoad();}}else scheduleLoad();}
window.Urban={get active(){return active},project:(x,y,z)=>screenProject(b.state,b.dimensions(),x,y,z),setView:applyView,get marker(){return renderer.marker},get mapLabels(){return context.labels},get selections(){return selections.map(f=>f.id)},solar:(date,minutes)=>solar(date,minutes,renderer.origin[1],renderer.origin[0],height||0),draw:()=>renderer.draw(solar(b.state.date,b.state.minutes,renderer.origin[1],renderer.origin[0],height||0)),pointerDown,pointerMove,pointerUp};
$('urbanMode').onclick=safe(async()=>{await ready;setActive(true);await changeMunicipality('tres-de-febrero');});
$('municipality').onchange=safe(e=>changeMunicipality(e.target.value));
$('clearSelection').onclick=()=>{selected=null;selections=[];footprint=null;height=0;applyView(true);sync();message(instructions);};
$('generate').onclick=safe(()=>{if(!selected)throw Error('Seleccioná una o más parcelas contiguas.');const v=getHeight();footprint=selected.geometry;height=v.h;heightInput=v.n;heightMode=v.mode;renderer.setOrigin(center(footprint));Object.assign(b.state,{panX:0,panY:0,zoom:Math.max(1.5,Math.min(3,b.state.zoom))});applyView(false);sync();message('Buscá una dirección o seleccioná una o varias parcelas contiguas, seleccioná la cantidad de pisos o altura de la nueva construcción y explorá los vecinos afectados por su sombra en distintas fechas y horarios.');scheduleLoad();community.event('simulation_created');});
for(const id of ['buildingHeight','heightMode'])$(id).oninput=safe(()=>{const v=getHeight();heightInput=v.n;heightMode=v.mode;if(height)height=v.h;sync();});
$('removeBuilding').onclick=()=>{height=0;footprint=selected?.geometry||null;applyView(true);sync();};
$('addressForm').onsubmit=safe(async e=>{e.preventDefault();searchRequest?.abort();searchRequest=new AbortController();$('searchResults').replaceChildren();message('Buscando dirección…');const results=await geocoder.search($('address').value,municipality,searchRequest.signal);message(results.length?'Elegí una coincidencia.':'No encontramos esa dirección. Probá agregando la localidad.');for(const result of results){const btn=document.createElement('button');btn.textContent=result.label;btn.onclick=safe(async()=>{renderer.marker={point:result.point,label:result.label,exact:result.exact};renderer.setOrigin(result.point);b.state.panX=b.state.panY=0;b.state.zoom=2.8;selected=null;selections=[];height=0;footprint=null;applyView(true);sync();await loadViewport();const f=repo.find(renderer.features,result.point);if(f&&result.exact)choose(f);else message(result.exact?'La dirección no coincide con una parcela disponible. Tocá una parcela cercana.':'El proveedor devolvió una ubicación aproximada, no la altura exacta. Revisá el mapa y tocá la parcela.');$('searchResults').replaceChildren();});$('searchResults').append(btn);}});
function listProjects(){const list=$('projectList');list.replaceChildren();for(const row of projects.list()){const div=document.createElement('div');div.className='saved-row';const name=document.createElement('input');name.value=row.name;name.setAttribute('aria-label','Nombre de simulación');name.onchange=safe(()=>projects.rename(row.id,name.value));div.append(name);for(const [label,action]of [['Abrir',async()=>{await restore(projects.open(row.id));$('projectsDialog').close();}],['Duplicar',()=>{projects.duplicate(row.id);listProjects();}],['Eliminar',()=>{projects.remove(row.id);listProjects();}]]){const btn=document.createElement('button');btn.textContent=label;btn.onclick=safe(action);div.append(btn);}list.append(div);}if(!list.children.length)list.textContent='Todavía no guardaste simulaciones.';}
$('saveProject').onclick=safe(()=>{projects.save(snapshot(),`${CONFIG.municipalities.find(m=>m.id===municipality).name} · ${height} m`);message('Simulación guardada en este dispositivo.');});$('savedProjects').onclick=safe(()=>{listProjects();$('projectsDialog').showModal();});
$('shareProject').onclick=safe(()=>{b.stop();const url=shareURL(snapshot());$('shareLink').value=url;$('qrArea').hidden=$('embedArea').hidden=true;$('shareMessage').textContent='El enlace contiene la geometría y los parámetros. Cualquiera que lo reciba puede verlos.';$('whatsapp').href='https://wa.me/?text='+encodeURIComponent('Mirá esta simulación de sombras de una construcción en esta parcela. '+url);$('shareDialog').showModal();community.event('simulation_shared');});
const shareSafe=fn=>async()=>{try{await fn();}catch(e){$('shareMessage').textContent=e.name==='AbortError'?'Compartir cancelado.':e.message;}};
$('copyLink').onclick=shareSafe(async()=>{await navigator.clipboard.writeText($('shareLink').value);$('shareMessage').textContent='Enlace copiado.';});
$('nativeShare').onclick=shareSafe(async()=>{if(navigator.share)await navigator.share({title:'Simulación de sombras',url:$('shareLink').value});else{await navigator.clipboard.writeText($('shareLink').value);$('shareMessage').textContent='Enlace copiado.';}});
$('showQR').onclick=shareSafe(async()=>{try{await QRCode.toCanvas($('qrCanvas'),$('shareLink').value,{width:280,margin:2,errorCorrectionLevel:'L'});$('qrArea').hidden=false;$('downloadQR').href=$('qrCanvas').toDataURL();}catch{throw Error('Esta geometría es demasiado detallada para un QR. Compartí el enlace.');}});
$('showEmbed').onclick=shareSafe(()=>{const url=shareURL(snapshot(),true);$('embedCode').value=`<iframe src="${url}" title="Simulación de asoleamiento" width="100%" height="650" style="border:0" loading="lazy" allowfullscreen></iframe>`;$('embedArea').hidden=false;community.event('embed_created');});$('copyEmbed').onclick=shareSafe(()=>navigator.clipboard.writeText($('embedCode').value));
$('aboutOpen').onclick=()=>$('aboutDialog').showModal();
$('googleBase').onclick=()=>message('Google Híbrido está preparado para activar cuando se configure una clave propia de Google Maps.');
$('cadastralBase').onclick=()=>message('Base catastral ARBA con calles y referencias de OpenStreetMap.');
$('coverageOpen').onclick=()=>{$('coverageDialog').showModal();};
document.querySelectorAll('[data-season]').forEach(btn=>btn.onclick=()=>{b.state.date=b.state.date.slice(0,4)+'-'+btn.dataset.season;$('date').value=b.state.date;b.update();});
b.canvas.addEventListener('wheel',scheduleLoad);b.canvas.addEventListener('keydown',scheduleLoad);for(const id of ['zoomIn','zoomOut','view2d','view3d','reset'])$(id).addEventListener('click',scheduleLoad);new ResizeObserver(()=>{if(active)scheduleLoad();}).observe(b.canvas);
ready=(async()=>{try{await Promise.all([repo.init(),context.init()]);}catch(e){message(e.message);}for(const m of CONFIG.municipalities){const o=document.createElement('option');o.value=m.id;o.textContent=m.name;const enabled=CONFIG.ENABLED_MUNICIPALITIES.includes(m.id)&&repo.manifest[m.id]?.available;o.disabled=!enabled;if(!enabled)o.textContent+=' · próximamente';$('municipality').append(o);const row=document.createElement('p'),data=repo.manifest[m.id];row.textContent=`${m.name} — ${data?.available&&CONFIG.ENABLED_MUNICIPALITIES.includes(m.id)?'Disponible · '+data.parcelCount+' parcelas · '+data.publishedAt:data?.status==='en-preparacion'?'En preparación':'Sin datos'}`;if(!data?.available||!CONFIG.ENABLED_MUNICIPALITIES.includes(m.id)){const vote=document.createElement('button');vote.textContent='Proponer '+m.name;vote.onclick=safe(async()=>{if(!community.enabled){vote.textContent='Votación no habilitada';return;}const key='amba.vote.'+m.id;if(localStorage.getItem(key)){vote.textContent='Ya propusiste este municipio';return;}if(await community.event('vote',m.id)){localStorage.setItem(key,'1');vote.textContent='Gracias por proponerlo';}else vote.textContent='Probá nuevamente más tarde';});row.append(vote);}$('coverageList').append(row);}$('municipality').value=municipality;$('licenseNote').textContent='Redistribución: pendiente de revisar condiciones con ARBA antes de publicar datasets derivados.';})();
ready.then(async()=>{if(location.pathname.startsWith('/embed')){document.body.classList.add('embed-mode');$('openFull').hidden=false;}if(location.hash){try{await restore(decode(location.hash));}catch(e){setActive(true);message(e.message);}}else{setActive(true);await changeMunicipality(municipality);}});
b.canvas.addEventListener('dblclick',e=>{if(!b.state.flat)return;renderer.setOrigin(renderer.point(e.clientX,e.clientY));b.state.panX=b.state.panY=0;b.state.zoom=Math.min(30,b.state.zoom*3);b.draw();scheduleLoad();});
window.addEventListener('hashchange',safe(()=>restore(decode(location.hash))));
