import {CONFIG} from '../config/app.js';
import {createUI} from './ui.js';
import {ParcelRepository} from './parcel-repository.js';
import {UrbanRenderer} from './renderer.js';
import {Geocoder} from './geocoder.js';
import {LocalProjects} from './local-projects.js';
import {solar} from './solar.js';
import {center,contains,footprintWithin,close,bounds} from './geometry.js';
import {shareURL,decode} from './share-state.js';
import QRCode from 'qrcode';
import {Community,supportAndAds} from './community.js';
const community=new Community();supportAndAds();community.init();
const $=id=>document.getElementById(id),b=window.Legacy;
createUI();
const repo=new ParcelRepository(),renderer=new UrbanRenderer(b),geocoder=new Geocoder(),projects=new LocalProjects();renderer.setOrigin(renderer.origin);
let active=false,municipality='tres-de-febrero',selected=null,draft=[],drawing=false,heightMode='meters',heightInput=24,height=0,footprint=null,request=null,loadTimer=null,start=null,dragVertex=-1,searchRequest=null,version='',ready;
const contacts=new Set();
const original={subtitle:document.querySelector('.brand small').textContent,heading:document.querySelector('.brand h1').innerHTML,intro:document.querySelector('header>.intro').textContent,badge:document.querySelector('.mapbadge').innerHTML,bottom:document.querySelector('.bottom').innerHTML};
const message=text=>$('urbanMessage').textContent=text;
const safe=fn=>async(...args)=>{try{return await fn(...args)}catch(e){message(e.message);}};
function setActive(value){active=value;document.body.classList.toggle('urban-active',value);document.title=value?'Mapa de sombras · AMBA':'Mapa de sombras · Proyecto Wernicke 2236';document.querySelector('.brand small').textContent=value?'Provincia de Buenos Aires · sin cuentas · guardado local':original.subtitle;b.stop();b.setSimulation('sun');$('explorer').hidden=!value;$('parcelPanel').hidden=!value||!selected;$('datasetCredit').hidden=!value;document.querySelector('.sound-modes').hidden=value;document.querySelector('.mapchoices>.viewtoggle').hidden=value;document.querySelector('.brand h1').innerHTML=value?'Mapa de sombras <span>· AMBA</span>':original.heading;document.querySelector('header>.intro').textContent=value?'Elegí una parcela, imaginá un edificio y explorá sus sombras.':original.intro;document.querySelector('.mapbadge').innerHTML=value?'Parcelario ARBA · norte geográfico':original.badge;document.querySelector('.bottom').innerHTML=value?'<span>Coordenadas geográficas · proyección local en metros</span><span>Estudio exploratorio</span>':original.bottom;b.update();}
function sync(){renderer.selected=selected;renderer.footprint=footprint;renderer.height=height;renderer.draft=draft;$('parcelPanel').hidden=!active||!selected;$('selectedLabel').textContent=selected?'Parcela seleccionada':'Parcela seleccionada';$('selectedLabel').title=selected?.id||'';$('drawingActions').hidden=!drawing;$('simulationActions').hidden=!height;$('editFootprint').hidden=!footprint;$('generate').disabled=!footprint||drawing;$('buildingHeight').value=heightInput;$('heightMode').value=heightMode;$('heightEquivalent').textContent=heightMode==='floors'?`${heightInput} pisos ≈ ${heightInput*CONFIG.DEFAULT_FLOOR_HEIGHT} m`:`${heightInput} m`;$('geoDebug').hidden=!CONFIG.DEBUG;if(selected)$('geoDebug').textContent=JSON.stringify({id:selected.id,coordinates:center(selected.geometry),bbox:bounds(selected.geometry),crs:'EPSG:4326',originalCRS:repo.manifest[municipality]?.originalCRS},null,2);b.update();}
async function loadViewport(){if(!active)return;request?.abort();request=new AbortController();const {width,height}=b.dimensions(),rect=b.canvas.getBoundingClientRect(),ps=[[0,0],[width,0],[0,height],[width,height]].map(p=>renderer.point(rect.left+p[0],rect.top+p[1])),bbox=[Math.min(...ps.map(p=>p[0])),Math.min(...ps.map(p=>p[1])),Math.max(...ps.map(p=>p[0])),Math.max(...ps.map(p=>p[1]))];try{const features=await repo.viewport(municipality,bbox,request.signal);renderer.features=features;if(selected&&!features.some(f=>f.id===selected.id))renderer.features.push(selected);if(!selected)message(features.length?'Tocá una parcela para empezar.':'No encontramos parcelas en esta vista. Explorá otra zona.');b.draw();}catch(e){if(e.name!=='AbortError')message(e.message);}}
function scheduleLoad(){clearTimeout(loadTimer);loadTimer=setTimeout(loadViewport,250);}
async function changeMunicipality(id){request?.abort();municipality=id;selected=null;draft=[];footprint=null;height=0;drawing=false;renderer.features=[];version=repo.manifest[id]?.version||'';const m=CONFIG.municipalities.find(m=>m.id===id);renderer.setOrigin(m.center||[-58.59,-34.59]);Object.assign(b.state,{panX:0,panY:0,zoom:2.8,yaw:-.35,pitch:.85});sync();const data=repo.manifest[id];$('datasetCredit').textContent=data?.available?`Fuente: ARBA · actualización ${data.publishedAt||'no informada'} · versión ${data.version}`:'Parcelario oficial todavía no disponible.';await loadViewport();}
function choose(f){selected=f;version=repo.manifest[municipality]?.version||version;draft=[];drawing=false;footprint=null;height=0;b.state.panX=0;b.state.panY=0;renderer.setOrigin(center(f.geometry));sync();message('¿Qué querés simular? Usá la parcela completa o dibujá el edificio.');scheduleLoad();}
function getHeight(){const n=Number($('buildingHeight').value),mode=$('heightMode').value,h=n*(mode==='floors'?CONFIG.DEFAULT_FLOOR_HEIGHT:1);if(!Number.isFinite(h)||h<=0||h>CONFIG.MAX_HEIGHT||(mode==='floors'&&!Number.isInteger(n)))throw Error(`Ingresá una altura entre 0 y ${CONFIG.MAX_HEIGHT} m, o pisos enteros equivalentes.`);return {n,mode,h};}
function snapshot(){if(!selected||!height||drawing)throw Error('Generá un volumen antes de guardar o compartir.');return {schemaVersion:1,municipality,parcel:{id:String(selected.id),geometry:selected.geometry},datasetVersion:version,footprint:footprint===selected.geometry?null:footprint.coordinates[0].slice(0,-1),height,heightMode,heightInput,date:b.state.date,minutes:Math.round(b.state.minutes),camera:Object.fromEntries(['yaw','pitch','zoom','panX','panY','flat'].map(k=>[k,b.state[k]]))};}
async function restore(s){await ready;municipality=s.municipality;$('municipality').value=municipality;selected={type:'Feature',id:s.parcel.id,properties:{municipality},geometry:s.parcel.geometry};version=s.datasetVersion;height=s.height;heightInput=s.heightInput;heightMode=s.heightMode;footprint=s.footprint?{type:'Polygon',coordinates:[close(s.footprint)]}:selected.geometry;draft=[];drawing=false;renderer.setOrigin(center(selected.geometry));renderer.features=[selected];setActive(true);Object.assign(b.state,s.camera,{date:s.date,minutes:s.minutes});$('date').value=s.date;sync();await loadViewport();if(repo.manifest[municipality]?.version!==version)message('El dataset cambió o no está disponible. Conservamos la geometría original del enlace.');$('openFull').href=shareURL(s);}
function pointerDown(e){if(!active)return false;contacts.add(e.pointerId);if(contacts.size>1){start=null;return drawing;}start={x:e.clientX,y:e.clientY,id:e.pointerId,multi:false};if(drawing){e.preventDefault();dragVertex=draft.findIndex(p=>Math.hypot(...renderer.screenPoint(p).map((v,i)=>v-(i?e.clientY-b.canvas.getBoundingClientRect().top:e.clientX-b.canvas.getBoundingClientRect().left)))<14);b.canvas.setPointerCapture(e.pointerId);return true;}return false;}
function pointerMove(e){if(!active)return false;const p=renderer.point(e.clientX,e.clientY);if(drawing){if(dragVertex>=0&&e.buttons&&contains(selected.geometry,p)){draft[dragVertex]=p;renderer.draft=draft;b.draw();}return true;}if(!e.buttons){const f=repo.find(renderer.features,p);if(renderer.hover!==f?.id){renderer.hover=f?.id;b.draw();}}return false;}
function pointerUp(e){contacts.delete(e.pointerId);if(!active||!start||start.id!==e.pointerId)return;const tap=e.type!=='pointercancel'&&Math.hypot(e.clientX-start.x,e.clientY-start.y)<6;start=null;if(drawing){if(tap&&dragVertex<0){const p=renderer.point(e.clientX,e.clientY);if(!contains(selected.geometry,p))message('Ese punto está fuera de la parcela. Elegí un punto interior.');else if(draft.length>=512)message('La huella alcanzó el máximo de 512 vértices.');else{draft.push(p);sync();}}dragVertex=-1;return;}if(tap){const f=repo.find(renderer.features,renderer.point(e.clientX,e.clientY));if(f)choose(f);}else scheduleLoad();}
window.Urban={get active(){return active},solar:(date,minutes)=>solar(date,minutes,renderer.origin[1],renderer.origin[0],height||0),draw:()=>renderer.draw(solar(b.state.date,b.state.minutes,renderer.origin[1],renderer.origin[0],height||0)),pointerDown,pointerMove,pointerUp};
$('urbanMode').onclick=safe(async()=>{await ready;setActive(true);await changeMunicipality($('municipality').value);});$('legacyMode').onclick=()=>setActive(false);
$('municipality').onchange=safe(e=>changeMunicipality(e.target.value));
$('useParcel').onclick=()=>{drawing=false;draft=[];footprint=selected.geometry;sync();};
$('drawFootprint').onclick=()=>{drawing=true;draft=[];height=0;footprint=null;b.setView(true);b.state.zoom=12;sync();message('Dibujá dentro de la parcela. Cerrá el polígono para continuar.');};
$('editFootprint').onclick=()=>{if(footprint.type!=='Polygon'||footprint.coordinates.length>1){message('Para editar una parcela con patios o varias partes, dibujá una nueva huella interior.');return;}draft=footprint.coordinates[0].slice(0,-1).map(p=>[...p]);drawing=true;height=0;b.setView(true);b.state.zoom=12;sync();};
$('undoPoint').onclick=()=>{draft.pop();sync();};$('resetPoints').onclick=()=>{draft=[];sync();};$('cancelDrawing').onclick=()=>{draft=[];drawing=false;sync();};
$('closePolygon').onclick=safe(()=>{if(!footprintWithin(selected.geometry,draft))throw Error('La huella debe tener al menos tres vértices, no cruzarse y quedar completamente dentro de la parcela, sin atravesar patios.');footprint={type:'Polygon',coordinates:[close(draft.map(p=>[...p]))]};draft=[];drawing=false;sync();});
$('generate').onclick=safe(()=>{if(drawing||!footprint)throw Error('Cerrá el dibujo o usá la parcela completa.');const v=getHeight();height=v.h;heightInput=v.n;heightMode=v.mode;b.setView(false);sync();message('Mové el horario para explorar las sombras.');community.event('simulation_created');});
for(const id of ['buildingHeight','heightMode'])$(id).oninput=safe(()=>{const v=getHeight();heightInput=v.n;heightMode=v.mode;if(height)height=v.h;sync();});
$('removeBuilding').onclick=()=>{height=0;footprint=null;draft=[];drawing=false;sync();};
$('addressForm').onsubmit=safe(async e=>{e.preventDefault();searchRequest?.abort();searchRequest=new AbortController();$('searchResults').replaceChildren();message('Buscando dirección…');const results=await geocoder.search($('address').value,municipality,searchRequest.signal);message(results.length?'Elegí una coincidencia.':'No encontramos esa dirección. Probá agregando la localidad.');for(const result of results){const btn=document.createElement('button');btn.textContent=result.label;btn.onclick=safe(async()=>{renderer.setOrigin(result.point);b.state.panX=b.state.panY=0;selected=null;height=0;footprint=null;sync();await loadViewport();const f=repo.find(renderer.features,result.point);if(f&&result.exact)choose(f);else message(result.exact?'La dirección no coincide con una parcela disponible. Tocá una parcela cercana.':'El proveedor devolvió una ubicación aproximada, no la altura exacta. Revisá el mapa y tocá la parcela.');$('searchResults').replaceChildren();});$('searchResults').append(btn);}});
function listProjects(){const list=$('projectList');list.replaceChildren();for(const row of projects.list()){const div=document.createElement('div');div.className='saved-row';const name=document.createElement('input');name.value=row.name;name.setAttribute('aria-label','Nombre de simulación');name.onchange=safe(()=>projects.rename(row.id,name.value));div.append(name);for(const [label,action]of [['Abrir',async()=>{await restore(projects.open(row.id));$('projectsDialog').close();}],['Duplicar',()=>{projects.duplicate(row.id);listProjects();}],['Eliminar',()=>{projects.remove(row.id);listProjects();}]]){const btn=document.createElement('button');btn.textContent=label;btn.onclick=safe(action);div.append(btn);}list.append(div);}if(!list.children.length)list.textContent='Todavía no guardaste simulaciones.';}
$('saveProject').onclick=safe(()=>{projects.save(snapshot(),`${CONFIG.municipalities.find(m=>m.id===municipality).name} · ${height} m`);message('Simulación guardada en este dispositivo.');});$('projectsOpen').onclick=safe(()=>{listProjects();$('projectsDialog').showModal();});
$('shareProject').onclick=safe(()=>{b.stop();const url=shareURL(snapshot());$('shareLink').value=url;$('qrArea').hidden=$('embedArea').hidden=true;$('shareMessage').textContent='El enlace contiene la geometría y los parámetros. Cualquiera que lo reciba puede verlos.';$('whatsapp').href='https://wa.me/?text='+encodeURIComponent('Mirá esta simulación de sombras de una construcción en esta parcela. '+url);$('shareDialog').showModal();community.event('simulation_shared');});
const shareSafe=fn=>async()=>{try{await fn();}catch(e){$('shareMessage').textContent=e.name==='AbortError'?'Compartir cancelado.':e.message;}};
$('copyLink').onclick=shareSafe(async()=>{await navigator.clipboard.writeText($('shareLink').value);$('shareMessage').textContent='Enlace copiado.';});
$('nativeShare').onclick=shareSafe(async()=>{if(navigator.share)await navigator.share({title:'Simulación de sombras',url:$('shareLink').value});else{await navigator.clipboard.writeText($('shareLink').value);$('shareMessage').textContent='Enlace copiado.';}});
$('showQR').onclick=shareSafe(async()=>{try{await QRCode.toCanvas($('qrCanvas'),$('shareLink').value,{width:280,margin:2,errorCorrectionLevel:'L'});$('qrArea').hidden=false;$('downloadQR').href=$('qrCanvas').toDataURL();}catch{throw Error('Esta geometría es demasiado detallada para un QR. Compartí el enlace.');}});
$('showEmbed').onclick=shareSafe(()=>{const url=shareURL(snapshot(),true);$('embedCode').value=`<iframe src="${url}" title="Simulación de asoleamiento" width="100%" height="650" style="border:0" loading="lazy" allowfullscreen></iframe>`;$('embedArea').hidden=false;community.event('embed_created');});$('copyEmbed').onclick=shareSafe(()=>navigator.clipboard.writeText($('embedCode').value));
$('coverageOpen').onclick=()=>{$('coverageDialog').showModal();};
document.querySelectorAll('[data-season]').forEach(btn=>btn.onclick=()=>{b.state.date=b.state.date.slice(0,4)+'-'+btn.dataset.season;$('date').value=b.state.date;b.update();});
b.canvas.addEventListener('wheel',scheduleLoad);b.canvas.addEventListener('keydown',scheduleLoad);for(const id of ['zoomIn','zoomOut','view2d','view3d','reset'])$(id).addEventListener('click',scheduleLoad);new ResizeObserver(()=>{if(active)scheduleLoad();}).observe(b.canvas);
ready=(async()=>{try{await repo.init();}catch(e){message(e.message);}for(const m of CONFIG.municipalities){const o=document.createElement('option');o.value=m.id;o.textContent=m.name;$('municipality').append(o);const row=document.createElement('p'),data=repo.manifest[m.id];row.textContent=`${m.name} — ${data?.available?'Disponible · '+data.parcelCount+' parcelas · '+data.publishedAt:data?.status==='en-preparacion'?'En preparación':'Sin datos'}`;if(!data?.available){const vote=document.createElement('button');vote.textContent='Proponer '+m.name;vote.onclick=safe(async()=>{if(!community.enabled){vote.textContent='Votación no habilitada';return;}const key='amba.vote.'+m.id;if(localStorage.getItem(key)){vote.textContent='Ya propusiste este municipio';return;}if(await community.event('vote',m.id)){localStorage.setItem(key,'1');vote.textContent='Gracias por proponerlo';}else vote.textContent='Probá nuevamente más tarde';});row.append(vote);}$('coverageList').append(row);}$('municipality').value=municipality;$('licenseNote').textContent='Redistribución: pendiente de revisar condiciones con ARBA antes de publicar datasets derivados.';})();
ready.then(async()=>{if(location.pathname.startsWith('/embed')){document.body.classList.add('embed-mode');$('openFull').hidden=false;}if(location.hash){try{await restore(decode(location.hash));}catch(e){setActive(true);message(e.message);}}else{setActive(true);await changeMunicipality(municipality);}});
window.addEventListener('hashchange',safe(()=>restore(decode(location.hash))));
