export class MapContext{
 constructor(){this.manifest={};this.cache=new Map();this.features=[];this.boundary=null;this.labels=[];}
 async init(){const index=await fetch('/data/context/manifest.json');if(index.ok)this.manifest=await index.json();this.boundaries={};await Promise.all(Object.keys(this.manifest).map(async id=>{const r=await fetch('/data/context/'+id+'-boundary.json');if(r.ok)this.boundaries[id]=(await r.json()).geometry;}));this.setMunicipality('tres-de-febrero');}
 setMunicipality(id){this.boundary=this.boundaries?.[id]||null;this.features=[];this.labels=[];}
 async load(id,bbox,signal,wide=false){const meta=this.manifest[id];if(!meta)return [];if(wide){const key=id+'/overview';if(!this.cache.has(key)){const r=await fetch('/data/context/'+key+'.json?v='+meta.version,{signal});if(!r.ok)throw Error('No pudimos cargar el mapa general.');this.cache.set(key,(await r.json()).features);}return this.cache.get(key);}const keys=[],size=meta.cellSize;for(let x=Math.floor(bbox[0]/size);x<=Math.floor(bbox[2]/size);x++)for(let y=Math.floor(bbox[1]/size);y<=Math.floor(bbox[3]/size);y++){const key=`${x}_${y}`;if(meta.cells.includes(key))keys.push(key);}const features=new Map();for(let i=0;i<keys.length;i+=6)await Promise.all(keys.slice(i,i+6).map(async key=>{const cacheKey=id+'/'+key;if(!this.cache.has(cacheKey)){const r=await fetch(`/data/context/${cacheKey}.json?v=${meta.version}`,{signal});if(!r.ok)throw Error('No pudimos cargar las calles.');this.cache.set(cacheKey,(await r.json()).features);if(this.cache.size>96)this.cache.delete(this.cache.keys().next().value);}for(const f of this.cache.get(cacheKey))features.set(f.id,f);}));return [...features.values()];}
 draw(renderer){const {ctx}=renderer.b,{width:W,height:H,scale}=renderer.b.dimensions();const boxes=[],used=new Set();this.labels=[];
  const label=(text,x,y,angle=0,color='#4c6263',priority=false)=>{if(!text||used.has(text)||x<20||x>W-35||y<90||y>H-45)return;ctx.font=`${priority?'600':'500'} ${priority?13:11}px "DM Sans", sans-serif`;const width=ctx.measureText(text).width;if(width>W*.8)return;const box=[x-width/2-5,y-10,x+width/2+5,y+10];if(boxes.some(b=>box[0]<b[2]&&box[2]>b[0]&&box[1]<b[3]&&box[3]>b[1]))return;boxes.push(box);used.add(text);this.labels.push(text);ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=4;ctx.strokeStyle='#fffffff2';ctx.strokeText(text,0,0);ctx.fillStyle=color;ctx.fillText(text,0,0);ctx.restore();};
  for(const f of this.features){const g=f.geometry,p=f.properties;if(g.type==='Point'){const xy=renderer.screenPoint(g.coordinates);if(p.kind==='station'){ctx.fillStyle='#466674';ctx.fillRect(xy[0]-3,xy[1]-3,6,6);}label((p.kind==='station'?'Est. ':'')+p.name,...xy,0,'#3f686b',true);continue;}if(p.kind==='park'){renderer.path(renderer.world(g),0,'#d8e8cf90','#a4bda1');const r=g.coordinates[0],mid=r.reduce((c,p)=>[c[0]+p[0]/r.length,c[1]+p[1]/r.length],[0,0]);if(scale>.15)label(p.name,...renderer.screenPoint(mid),0,'#537350',true);continue;}
   const pts=g.coordinates.map(p=>renderer.screenPoint(p));if(pts.length<2)continue;
   const major=['motorway','trunk','primary','secondary','tertiary'].includes(p.roadClass);if(scale<.12&&!major&&p.kind==='road')continue;
   ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.strokeStyle=p.kind==='water'?'#a1c5ce':p.kind==='rail'?'#8e9999':major?'#d9cbb1':'#d4ddda';ctx.lineWidth=p.kind==='rail'?2:major?Math.max(2,Math.min(8,scale*8)):Math.max(1,Math.min(5,scale*5));ctx.setLineDash(p.kind==='rail'?[5,4]:[]);ctx.stroke();ctx.setLineDash([]);
   const segments=pts.slice(1).map((b,i)=>({a:pts[i],b,length:Math.hypot(b[0]-pts[i][0],b[1]-pts[i][1])})).filter(s=>s.a[0]>-W&&s.a[0]<W*2&&s.a[1]>-H&&s.a[1]<H*2).sort((a,b)=>b.length-a.length);
   for(const s of segments){if(s.length<Math.min(130,p.name.length*5.5))continue;const x=(s.a[0]+s.b[0])/2,y=(s.a[1]+s.b[1])/2;let angle=Math.atan2(s.b[1]-s.a[1],s.b[0]-s.a[0]);if(angle>Math.PI/2)angle-=Math.PI;if(angle< -Math.PI/2)angle+=Math.PI;label(p.name,x,y,angle);if(used.has(p.name))break;}
  }
 }
}
