import {groundPoint} from './camera.js';
import {polygons,localProjection,shadow,overlaps} from './geometry.js';
export class UrbanRenderer{
 constructor(bridge){this.b=bridge;this.origin=[-58.590636,-34.592113];this.features=[];this.selected=null;this.hover=null;this.footprint=null;this.height=0;this.shadowKey='';this.shadow=[];this.context=null;this.marker=null;this.selectedIds=new Set();}
 setOrigin(p){this.origin=p;this.projection=localProjection(p);this.shadowKey='';}
 world(g){return {type:g.type,coordinates:g.type==='Polygon'?g.coordinates.map(r=>r.map(p=>this.projection.forward(p))):g.coordinates.map(poly=>poly.map(r=>r.map(p=>this.projection.forward(p))))};}
 screenPoint(p){return this.b.project(...this.projection.forward(p));}
 point(clientX,clientY){const rect=this.b.canvas.getBoundingClientRect();return this.projection.inverse(groundPoint(this.b.state,this.b.dimensions(),clientX-rect.left,clientY-rect.top));}
 path(g,z=0,fill,stroke){const ctx=this.b.ctx;ctx.beginPath();for(const poly of polygons(g))for(const ring of poly){ring.forEach((p,i)=>{const xy=this.b.project(p[0],p[1],z);i?ctx.lineTo(...xy):ctx.moveTo(...xy)});ctx.closePath();}if(fill){ctx.fillStyle=fill;ctx.fill('evenodd');}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke();}}
 draw(sun){const {ctx,state}=this.b,{width:W,height:H}=this.b.dimensions();this.b.setScale(Math.min(W,H)/480*state.zoom);ctx.clearRect(0,0,W,H);ctx.fillStyle='#edf1ef';ctx.fillRect(0,0,W,H);if(this.context?.boundary)this.path(this.world(this.context.boundary),0,'#f7f7ee','#b6b797');const world=this.features.map(f=>({...f,geometry:this.world(f.geometry)}));for(const f of world)this.path(f.geometry,0,this.selectedIds.has(String(f.id))?'#f9dfaf':f.id===this.hover?'#f7e6c9':'#fafbf8','#a9bbb6');
 if(this.context)this.context.draw(this);
 if(this.height&&this.footprint){const g=this.world(this.footprint),key=JSON.stringify([g,this.height,sun.east,sun.north,sun.up]);if(key!==this.shadowKey){this.shadowKey=key;this.shadow=shadow(g,this.height,sun);}if(this.shadow.length)this.path({type:'MultiPolygon',coordinates:this.shadow},0,'#274e745f','#244e78');const hits=world.filter(f=>!this.selectedIds.has(String(f.id))&&overlaps(f.geometry,this.shadow));for(const f of hits)this.path(f.geometry,0,'#f4774920','#bd3a19');document.getElementById('affectedCount').textContent=String(hits.length);document.getElementById('impactScope').textContent='Parcelas cargadas en esta vista · conteo parcial';this.volume(g,this.height);}
 else{document.getElementById('affectedCount').textContent='0';document.getElementById('impactScope').textContent='Elegí una parcela y generá un volumen.';}
 if(this.selected)this.path(this.world(this.selected.geometry),0,null,'#a96a16');
 if(this.marker){const p=this.screenPoint(this.marker.point);ctx.save();ctx.beginPath();ctx.arc(...p,8,0,Math.PI*2);ctx.fillStyle='#d52d2d';ctx.fill();ctx.lineWidth=3;ctx.strokeStyle='#fff';ctx.stroke();ctx.font='600 12px sans-serif';ctx.textAlign='center';ctx.lineWidth=4;ctx.strokeText(this.marker.exact?'Dirección buscada':'Ubicación aproximada',p[0],p[1]-17);ctx.fillStyle='#a32020';ctx.fillText(this.marker.exact?'Dirección buscada':'Ubicación aproximada',p[0],p[1]-17);ctx.restore();}
 ctx.fillStyle='#23484c';ctx.font='bold 12px sans-serif';const n=this.b.project(0,50),o=this.b.project(0,0);ctx.fillText('N',W-49,100);const angle=Math.atan2(n[1]-o[1],n[0]-o[0]);ctx.beginPath();ctx.moveTo(W-45,130);ctx.lineTo(W-45+Math.cos(angle)*20,130+Math.sin(angle)*20);ctx.strokeStyle='#a96a16';ctx.lineWidth=2;ctx.stroke();}
 volume(g,height){const {state}=this.b,faces=[];if(!state.flat)for(const poly of polygons(g))for(const r of poly)for(let i=0;i<r.length-1;i++){const a=r[i],b=r[i+1];faces.push({p:[[...a,0],[...b,0],[...b,height],[...a,height]],fill:['#c38b38','#d6a04e','#e5b667','#be8d3e'][i%4]});}const depth=p=>(p[0]*Math.sin(state.yaw)+p[1]*Math.cos(state.yaw))*Math.sin(state.pitch)-p[2]*Math.cos(state.pitch);faces.sort((a,b)=>b.p.reduce((s,p)=>s+depth(p),0)-a.p.reduce((s,p)=>s+depth(p),0));for(const f of faces){this.b.polygon(f.p,f.fill,'#8d581b');for(let z=3;z<height;z+=3)this.b.line(f.p.slice(0,2).map(p=>[p[0],p[1],z]),'#f7d38a',.6);}this.path(g,height,'#efb74c','#8d581b');}
}
