import {compressSync,decompressSync,strToU8,strFromU8} from 'fflate';
import {connected,mergeParcels} from './parcel-selection.js';
import {CONFIG} from '../config/app.js';
import {polygons,validRing,footprintWithin} from './geometry.js';
const fail=()=>{throw Error('El enlace está dañado o usa una versión no compatible.');};
export function validate(s){if(!s||s.schemaVersion!==1||!CONFIG.municipalities.some(m=>m.id===s.municipality)||!s.parcel||typeof s.parcel.id!=='string'||typeof s.datasetVersion!=='string'||!['Polygon','MultiPolygon'].includes(s.parcel.geometry?.type))fail();const ps=polygons(s.parcel.geometry);if(!Array.isArray(ps)||ps.length>32||!ps.length)fail();let count=0;for(const p of ps){if(!Array.isArray(p)||!p.length)fail();for(const ring of p){if(!Array.isArray(ring)||ring.length<4||JSON.stringify(ring[0])!==JSON.stringify(ring.at(-1)))fail();count+=ring.length;if(count>3000||!ring.every(v=>Array.isArray(v)&&v.length===2&&v.every(Number.isFinite)&&v[0]>=-60&&v[0]<=-57&&v[1]>=-36&&v[1]<=-33)||!validRing(ring.slice(0,-1)))fail();}}if(!Number.isFinite(s.height)||s.height<=0||s.height>CONFIG.MAX_HEIGHT||!['meters','floors'].includes(s.heightMode)||(s.heightMode==='floors'&&!Number.isInteger(s.heightInput))||!Number.isFinite(s.heightInput)||s.heightInput<=0||Math.abs(s.heightInput*(s.heightMode==='floors'?CONFIG.DEFAULT_FLOOR_HEIGHT:1)-s.height)>1e-6)fail();if(s.footprint&&!footprintWithin(s.parcel.geometry,s.footprint))fail();if(!/^\d{4}-\d{2}-\d{2}$/.test(s.date)||s.date<'2020-01-01'||s.date>'2100-12-31'||new Date(s.date+'T12:00:00Z').toISOString().slice(0,10)!==s.date||!Number.isInteger(s.minutes)||s.minutes<0||s.minutes>1439)fail();const c=s.camera;if(!c||!['yaw','pitch','zoom','panX','panY'].every(k=>Number.isFinite(c[k]))||c.zoom<.006||c.zoom>30||c.pitch<.25||c.pitch>1.2||Math.abs(c.panX)>1e6||Math.abs(c.panY)>1e6||typeof c.flat!=='boolean')fail();if(s.parcels!==undefined){if(!Array.isArray(s.parcels)||!s.parcels.length||s.parcels.length>16||new Set(s.parcels.map(p=>p.id)).size!==s.parcels.length)fail();for(const parcel of s.parcels)validate({...s,parcels:undefined,parcel,footprint:null});if(!connected(s.parcels))fail();const combined=mergeParcels(s.parcels);if(JSON.stringify(combined.geometry)!==JSON.stringify(s.parcel.geometry)&&s.parcels.length>1)fail();}return s;}
export function encode(s){validate(s);const bytes=compressSync(strToU8(JSON.stringify(s)),{level:9});return '#v1='+btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');}
export function decode(hash){try{if(!/^#v1=[A-Za-z0-9_-]+$/.test(hash)||hash.length>30000)fail();const bytes=Uint8Array.from(atob(hash.slice(4).replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));const size=new DataView(bytes.buffer).getUint32(bytes.length-4,true);if(size>200000)fail();return validate(JSON.parse(strFromU8(decompressSync(bytes))));}catch{fail();}}
export const shareURL=(s,embed=false)=>new URL((embed?'/embed/':'/')+encode(s),location.origin).href;
